apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  id: my-db-aws
  compositionSelector:
    matchLabels:
      provider: aws
      db: postgresql
  parameters:
    version: "13.4"
    size: medium
    databases:
      - db-01
      - db-02
      - db-03
