---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    crossplane.io/composition-resource-name: my-db-aws-db-01
    crossplane.io/external-name: db-01
  labels:
    crossplane.io/claim-name: my-db
  name: my-db-aws-db-01
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: SQL
spec:
  forProvider: {}
  providerConfigRef:
    name: my-db-aws
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    crossplane.io/composition-resource-name: my-db-aws-db-02
    crossplane.io/external-name: db-02
  labels:
    crossplane.io/claim-name: my-db
  name: my-db-aws-db-02
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: SQL
spec:
  forProvider: {}
  providerConfigRef:
    name: my-db-aws
---
apiVersion: postgresql.sql.crossplane.io/v1alpha1
kind: Database
metadata:
  annotations:
    crossplane.io/composition-resource-name: my-db-aws-db-03
    crossplane.io/external-name: db-03
  labels:
    crossplane.io/claim-name: my-db
  name: my-db-aws-db-03
  ownerReferences:
  - apiVersion: devopstoolkitseries.com/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: SQL
spec:
  forProvider: {}
  providerConfigRef:
    name: my-db-aws
