apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  compositionRef:
    name: google-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: google
  id: my-db-google
  parameters:
    size: medium
    version: "13.4"
  resourceRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQL
