---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQL
metadata:
  labels:
    crossplane.io/claim-name: my-db
spec:
  claimRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQLClaim
    name: my-db
  compositionRef:
    name: google-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: google
  compositionUpdatePolicy: Automatic
  id: my-db-google
  parameters:
    size: medium
    version: "13.4"
  resourceRefs:
  - apiVersion: kubernetes.crossplane.io/v1alpha2
    kind: Object
    name: my-db-google-schema-db-01
  - apiVersion: kubernetes.crossplane.io/v1alpha2
    kind: Object
    name: my-db-google-schema-db-02
  - apiVersion: kubernetes.crossplane.io/v1alpha2
    kind: Object
    name: my-db-google-secret
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: Database
    name: my-db-google-db-01
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: Database
    name: my-db-google-db-02
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: Database
    name: my-db-google-db-03
  - apiVersion: postgresql.sql.crossplane.io/v1alpha1
    kind: ProviderConfig
    name: my-db-google
  - apiVersion: sql.gcp.upbound.io/v1beta1
    kind: DatabaseInstance
    name: my-db-google
  - apiVersion: sql.gcp.upbound.io/v1beta1
    kind: User
    name: my-db-google
