apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  compositionRef:
    name: azure-postgresql
  compositionSelector:
    matchLabels:
      db: postgresql
      provider: azure
  id: my-db-azure
  parameters:
    size: medium
    version: "13.4"
  resourceRef:
    apiVersion: devopstoolkitseries.com/v1alpha1
    kind: SQL
