---
apiVersion: v1
kind: Secret
metadata:
  name: my-db-azure-password
data:
  password: cG9zdGdyZXM=
---
apiVersion: devopstoolkitseries.com/v1alpha1
kind: SQLClaim
metadata:
  name: my-db
spec:
  id: my-db-azure
  compositionSelector:
    matchLabels:
      provider: azure
      db: postgresql
  parameters:
    version: "13.4"
    size: medium
